class Const{
  static const reportAttrKeys = {
  'prod_normal': 'Œufs normaux',
  'prod_dj': 'Œufs double jaune',
  'prod_blanc': 'Œufs blancs',
  'prod_casse': 'Cassé',
  'prod_feles': 'Sale',
  'prod_liquide': 'Éliminés (kg)',
  'prod_elimne': 'Triage',
  'pmo': 'PMO (g)',
  'start_picking': 'Heure début ramassage',
  'end_picking': 'Heure Fin ramassage',
  'coloration': 'Coloration',
  'qty_shell': 'Qualité de Coquille',
  'mort': 'Mortalité (Sujet)',
  'hensEliminated': 'Triage (Sujet)',
  'poidVif': 'Poids corporel (g)',
  'homog': 'Homogeneité (%)',
  'alimentDist': 'Aliment consommé (Kg)',
  'eauDist': 'Eau consommée (Litre)',
  'delivered_alt': 'Aliment reçu (Kg)',
  'alt_unit_price': 'Prix unitaire',
  'formule': "Référence d'aliment",
  'temperatureMin': 'Température intérieure minimale',
  'temperatureMax': 'Température intérieure maximale',
  'temperatureMinExt': 'Température extérieure minimale',
  'temperatureMaxExt': 'Température extérieure maximale',
  'humidity': 'Humidité (%)',
  'lightOn': 'Allumage de lumiére',
  'lightOff': 'Extinction de lumiére',
  'lightDuration': 'Durée de lumiére',
  'flashOn': 'Allumage de flash',
  'flashOff': 'Extinction de flash',
  'flashDuration': 'Duré de flash',
  'intensite': 'Intensité',
  'intensIsLux': 'intensité',
  'hensReformedNormal': 'Sujets normaux',
  'reform_price': 'Prix unitaire',
  'reform_is_kg': 'Réforme en kg',
  'hensReformedTriage': 'Sujets triage',
  'triage_price': 'Prix unitaire',
  'triage_is_kg': 'Triage en kg',
  'hensReformedFree': 'Sujets gratuits'
};
}