name: farmdrivermobile
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  carousel_slider_plus: ^7.0.0
  syncfusion_flutter_core: ^26.2.8
  syncfusion_flutter_charts: ^26.2.8
  syncfusion_flutter_datagrid: ^26.2.8
  syncfusion_flutter_pdfviewer: ^26.2.11
  page_transition: ^2.1.0
  share_plus: ^10.0.0
  timeline_tile: ^2.0.0
  readmore: ^3.0.0
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  jwt_decode: ^0.3.1
  material_design_icons_flutter: ^7.0.7296
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^3.0.1
  path_provider: ^2.1.2
  awesome_notifications: ^0.9.3+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_ringtone_player: ^4.0.0+3
  image_picker: ^1.0.4
  firebase_core: ^2.24.2
  firebase_messaging:
  flutter_localizations:
    sdk: flutter
  firebase_analytics: ^10.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
